chore(CI): Make `files_external` CI workflows consistent
Signed-off-by: Ferdinand Thiessen <opensource@fthiessen.de>

diff --git a/.github/workflows/files-external-sftp.yml b/.github/workflows/files-external-sftp.yml
--- a/.github/workflows/files-external-sftp.yml
+++ b/.github/workflows/files-external-sftp.yml
@@ -1,11 +1,11 @@
-name: PHPUnit files_external WebDAV
+name: PHPUnit files_external sFTP
 on:
   pull_request:
   schedule:
     - cron: "5 2 * * *"
-
+  
 concurrency:
-  group: files-external-webdav-${{ github.head_ref || github.run_id }}
+  group: files-external-sftp-${{ github.head_ref || github.run_id }}
   cancel-in-progress: true
 
 jobs:
@@ -31,26 +31,23 @@ jobs:
               - 'composer.lock'
               - '**.php'
 
-  files-external-webdav-apache:
+  files-external-sftp:
     runs-on: ubuntu-latest
     needs: changes
 
     if: ${{ github.repository_owner != 'nextcloud-gmbh' && needs.changes.outputs.src != 'false' }}
 
     strategy:
+      # do not stop on another job's failure
+      fail-fast: false
       matrix:
-        php-versions: ['8.0', '8.1', '8.2', '8.3']
+        php-versions: ['8.0', '8.3']
+        sftpd: ['openssh']
         include:
-          - php-versions: '8.2'
+          - php-versions: '8.0'
             coverage: ${{ github.event_name != 'pull_request' }}
 
-    name: php${{ matrix.php-versions }}-webdav
-
-    services:
-      apache:
-        image: ghcr.io/nextcloud/continuous-integration-webdav-apache:latest
-        ports:
-          - 8081:80
+    name: php${{ matrix.php-versions }}-${{ matrix.sftpd }}
 
     steps:
       - name: Checkout server
@@ -58,48 +55,55 @@ jobs:
         with:
           submodules: true
 
+      - name: Set up sftpd
+        run: |
+          sudo mkdir /tmp/sftp
+          sudo chown -R 0777 /tmp/sftp
+          if [[ "${{ matrix.sftpd }}" == 'openssh' ]]; then docker run -p 2222:22 --name sftp -d -v /tmp/sftp:/home/test atmoz/sftp "test:test:::data"; fi
+
       - name: Set up php ${{ matrix.php-versions }}
-        uses: shivammathur/setup-php@4bd44f22a98a19e0950cbad5f31095157cc9621b # v2
+        uses: shivammathur/setup-php@c5fc0d8281aba02c7fda07d3a70cc5371548067d #v2.25.2
         with:
           php-version: ${{ matrix.php-versions }}
           # https://docs.nextcloud.com/server/stable/admin_manual/installation/source_installation.html#prerequisites-for-manual-installation
-          extensions: bz2, ctype, curl, dom, fileinfo, gd, iconv, intl, json, libxml, mbstring, openssl, pcntl, posix, redis, session, simplexml, xmlreader, xmlwriter, zip, zlib, sqlite, pdo_sqlite
+          extensions: ctype, curl, dom, fileinfo, gd, iconv, intl, json, libxml, mbstring, openssl, pcntl, posix, redis, session, simplexml, xmlreader, xmlwriter, zip, zlib, sqlite, pdo_sqlite
           coverage: ${{ matrix.coverage && 'xdebug' || 'none' }}
-          ini-file: development
         env:
           GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
 
       - name: Set up Nextcloud
         run: |
           composer install
+          mkdir data
           ./occ maintenance:install --verbose --database=sqlite --database-name=nextcloud --database-host=127.0.0.1 --database-user=root --database-pass=rootpassword --admin-user admin --admin-pass password
-          ./occ config:system:set --value true --type boolean allow_local_remote_servers
           ./occ app:enable --force files_external
-          echo "<?php return ['run' => true, 'host' => 'localhost:8081/webdav/', 'user' => 'test', 'password'=>'pass', 'root' => '', 'wait' => 0];" > apps/files_external/tests/config.webdav.php
-
-      - name: Wait for WebDAV
-        run: |
-          sleep 5
-          curl -f -m 1 --retry-connrefused --retry 10 --retry-delay 10 http://test:pass@localhost:8081/webdav/
+          echo "<?php return ['run' => true, 'host' => 'localhost:2222','user' => 'test','password' => 'test', 'root' => 'data'];" > apps/files_external/tests/config.sftp.php
 
       - name: PHPUnit
-        run: composer run test:files_external -- --verbose \
-          apps/files_external/tests/Storage/WebdavTest.php \
+        run: composer run test:files_external -- \
+          apps/files_external/tests/Storage/SftpTest.php \
+          apps/files_external/tests/Storage/SFTP_KeyTest.php \
           ${{ matrix.coverage && ' --coverage-clover ./clover.xml' || '' }}
 
       - name: Upload code coverage
         if: ${{ !cancelled() && matrix.coverage }}
-        uses: codecov/codecov-action@4fe8c5f003fae66aa5ebb77cfd3e7bfbbda0b6b0 # v3.1.5
+        uses: codecov/codecov-action@v3
         with:
           files: ./clover.xml
-          flags: phpunit-files-external-webdav
+          flags: phpunit-files-external-sftp
 
-  files-external-webdav-summary:
+      - name: sftpd logs
+        if: always()
+        run: |
+          ls -l /tmp/sftp
+          docker logs sftp
+
+  sftp-summary:
     runs-on: ubuntu-latest-low
-    needs: [changes, files-external-webdav-apache]
+    needs: [changes, files-external-sftp]
 
     if: always()
 
     steps:
       - name: Summary status
-        run: if ${{ needs.changes.outputs.src != 'false' && needs.files-external-webdav-apache.result != 'success' }}; then exit 1; fi
+        run: if ${{ needs.changes.outputs.src != 'false' && needs.files-external-sftp.result != 'success' }}; then exit 1; fi
